version: "3.9"
services:
  apache-php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - lamp-network
  phpmyadmin:
    image: phpmyadmin
    links:
      - mariadb:db
    ports:
      - "8080:80"
    networks:
      - lamp-network
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    command: --lower_case_table_names=1
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - lamp-network
    environment:
      MARIADB_ROOT_PASSWORD: admin

volumes:
    mariadb:

networks:
    lamp-network:
      name: lamp-network
