version: "3.9"
services:
  apache-php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
  phpmyadmin:
    image: phpmyadmin
    links:
      - mariadb:db
    ports:
      - "8080:80"
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    command: --lower_case_table_names=1
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: azpoazui

volumes:
    mariadb: