version: "3.9"
services:
  apache-php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ${PWD}/html:/var/www/html
      - ${PWD}/config/php/:/usr/local/etc/php/
  phpmyadmin:
    image: phpmyadmin
    links:
      - mariadb:db
    ports:
      - "8080:80"
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: admin

volumes:
    mariadb: